version: 2

project_name: abacatepay

before:
  hooks:
    - go mod tidy

builds:
  - id: abacatepay
    binary: abacatepay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Alias (abkt)
  - id: abkt
    binary: abkt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - abacatepay
      - abkt
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: false
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Homebrew
brews:
  - name: abacatepay
    repository:
      owner: AbacatePay
      name: homebrew-tap
    folder: Formula
    homepage: https://abacatepay.com
    description: AbacatePay’s developer-first CLI for APIs and local workflows 
    license: MIT
    install: |
      bin.install "abacatepay"
      bin.install "abkt"

# Autocomplete
completions:
  bash:
    name: abacatepay
  zsh:
    name: _abacatepay
  fish:
    name: abacatepay.fish
